### PR TITLE
[v1] Adds Underlines and double underlines

### PR DESCRIPTION
**Pull request by isralduke**
This PR:

- adds underlines upon hover to many buttons to indicate hover status
- adds double underline style upon hover to links in text to indicate hover status

This needs to be done because our styles currently rely on subtle color changes right now and this is not good practice.

This video presents a before and after : https://share.cleanshot.com/6XpDq821

### CODE REVIEW

**Review by isralduke — COMMENTED** [review]
These changes are good. We also already have them in V2

**Review by isralduke — COMMENTED** [review]
These are good changes

**Comment by james-alt** [comment]
This one will require bumping the version number and pushing to NPM.

**Review by james-alt — APPROVED** [review]
Looks good :shipit:

**Pull request merged**
