### PR TITLE
Replace inline skiplink markup with partial

### PR DESCRIPTION
**Pull request by isralduke**
This PR:

- replaces inline markup for the skip link with a partial

### CODE REVIEW

**Review by frogpad7 — COMMENTED** [review]
Did you want to also replace the skip-link that is hard-coded inside the app-screen.njk with a partial as well?

**Review by frogpad7 — APPROVED** [review]
Partials are utilized everywhere!

**Review by james-alt — APPROVED** [review]
:shipit:

**Review by rltucker — APPROVED** [review]
Good

**Pull request merged**
